[build]
dockerfile = "Dockerfile"

[deploy]
startCommand = "php -S 0.0.0.0:8080"
port = 8080

[[services]]
name = "web"
builder = "dockerfile"

[variables]
MYSQLHOST = "localhost"
MYSQLPORT = "3306"
MYSQLUSER = "root"
MYSQLDATABASE = "railway"
